name: Release Gems
description: Build and publish Ruby gems

branding:
  icon: package
  color: red

runs:
  using: composite
  steps:
  - name: Error
    run: |
      echo '::error::Do not use this action directly. Read [the documentation](https://github.com/release-gems/action?tab=readme-ov-file#quick-start) for set up.'
      exit 1
    shell: bash
